# Generated by Django 4.2.6 on 2024-02-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quant',
            new_name='quantity',
        ),
    ]
